version: '3'

services:
  hono-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=honodb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - APP_STRAPI_API_URL=http://host.docker.internal:1338
      - APP_STRAPI_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM5Njc2ODE2LCJleHAiOjE3NDIyNjg4MTZ9.9QWLLQKK6FTc_aoasV70hGOkbP5UrwLnkqCK7h_TVQA
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    command: >
      sh -c "npm install && npm run dev"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=honodb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  node_modules: 